[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
fs_permissions = [
    { access = "read", path = "./whir-helper/proof_output_1.json"},
    { access = "read", path = "./whir-helper/proof_output_10_1.json"},
    { access = "read", path = "./whir-helper/proof_output_10_10.json"},
    { access = "read", path = "./whir-helper/proof_output_10_100.json"},
    { access = "read", path = "./whir-helper/proof_output_20_1.json"},
    { access = "read", path = "./whir-helper/proof_output_20_10.json"},
    { access = "read", path = "./whir-helper/proof_output_20_100.json"},
]

